name: Cleanup Preview Deployments
run-name: "Cleanup preview (${{ github.head_ref }})"

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [closed]

permissions:
  deployments: write

jobs:
  deactivate-preview:
    name: Deactivate preview deployments
    runs-on: ubuntu-latest
    steps:
      - name: Deactivate preview deployments
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            const deployments = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment: 'preview',
              ref: context.payload.pull_request.head.ref,
              per_page: 100,
            });
            for (const deployment of deployments.data) {
              await github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: deployment.id,
                state: 'inactive',
              });
            }
