name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  gcp-deploy:
    name: GCP Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo theme
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.76.5"
          extended: true
      - name: Build
        run: hugo --minify --source resume
      - name: Deploy to Google App Engine
        uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: true
          version: ${{ github.sha }}
